### ISSUE TITLE
Основной цвет

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#13]
- [x] Пожалуйста, только не рыжий!!!

**Comment by Mazdaywik** [comment]
```HTML
<body bgcolor=batman>
```
```HTML
<body bgcolor=cat-and-dog>
```
```HTML
<body bgcolor=dog-and-cat>
```
```HTML
<body bgcolor=beer>
```
```HTML
<body bgcolor=vodka>
```
```HTML
<body bgcolor=hell>
```
```HTML
<body bgcolor=heaven>
```
Выбирайте любой!

В CSS эти цвета не работают, только в HTML.

**Comment by Mazdaywik** [comment]
Про то, откуда взялись цвета из предыдущего комментария: <https://habr.com/ru/post/173727>. А про цвета `beer` и `vodka` — старая шутка. Я её слышал как якобы пасхалку ещё в детстве.

Проектам УТП со статическими сайтами я сделал заготовку `index.html`, которая отображается в GitHub Pages. Некоторые команды заготовку уже переделали, а некоторые нет. В заготовке я использовал вышеупомянутые цвета:

* https://github.com/bmstu-iu9/utp2020-5-2d-game/blob/master/index.html
  https://bmstu-iu9.github.io/utp2020-5-2d-game/
* https://github.com/bmstu-iu9/utp2020-9-2d-game/blob/master/index.html
  https://bmstu-iu9.github.io/utp2020-9-2d-game/
* https://github.com/bmstu-iu9/utp2020-3-2d-game/blob/master/index.html
  https://bmstu-iu9.github.io/utp2020-3-2d-game/ (на Windows шрифт отображается правильно только в Internet Explorer)
