### ISSUE TITLE
Единство оформления

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#19]
### Привести дизайн страницы регистрации по подобию со страницей авторизации:
* [x] Изменить цвета
* [x] Добавить блоки с надписями и картинками вместо их включения в фон
* [x] Добавить блок-обертку для полей ввода
* [x] Изменить обычные кнопки на псевдокнопки с оформлением

P.S. для работы создал ветку redesign-registration

**Comment by YakushevK** [comment]
Вопрос решен
