### ISSUE TITLE
Первичное оформление 

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#2]
# Оформление страницы ввода и регистрации:
* [x] Создать шаблон страницы ввода логина и пароля
* [x] Создать шаблон страницы регистрации
* [x] Добавить переход от авторизации к регистрации

**Comment by Mazdaywik** [comment]
После `#` должен быть знак пробела:
```Markdown
#Оформление страницы ввода и регистрации:
```

Перед `[ ]` нужно поставить `*`:
```Markdown
* [ ] Создать шаблон страницы ввода логина и пароля
```

**Comment by not-Whale** [comment]
Исправил. Спасибо!

**Comment by not-Whale** [comment]
@YakushevK @MaksimKoster @maxevg
