### ISSUE TITLE
Структурирование страницы чата

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#26]
### Блочное структурирование меню должно быть следующим:
* [x] Отступы от краев окна браузера сужают рабочую область
* [x] Слева располагается (занимая примерно треть рабочей области) список пользователей в комнате/чате
* [x] Над списком пользователей располагается поисковая строка по имени пользователя
* [x] Справа располагается (занимая примерно две трети рабочей области) окно чата
* [x] Над чатом располагается информация о комнате/чате
* [x] Сверху располагается тулбар
* [x] На тулбаре: кнопка выхода из комнаты/чата, кнопка возврата в меню, кнопки навигации и помощи

**Comment by maxevg** [comment]
Вопрос выполнен
