### ISSUE TITLE
Цветовой индикатор некорректных входных данных: Регистрация

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#27]
- [x] В случае некорректного вида логина/пароля/имени обводить окно ввода красным цветом, отмечая, где пользователь ошибся

**Comment by Mazdaywik** [comment]
Имейте ввиду это: https://t.me/ilyabirman_channel/6078

**Comment by maxevg** [comment]
Вопрос решён
