### ISSUE TITLE
Первичное оформление страниц: Заметки

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#5]
### Общие договоренности:
* [x] Сужение рабочей области (не должна занимать весь экран в ширину, лучше добавить разгружающее глаз пространство по бокам страницы)
* [x] Цвет не играет роли (обратить большее внимание на структурное оформление страницы, а не цветовую гамму)
***
### Меню чатов:
* [x] Создать верхнее меню-полоску (название, настройки, вход/выход)

**Comment by YakushevK** [comment]
Первичное оформление сделано

**Comment by Mazdaywik** [comment]
Надо в названия коммитов, в которых сделано, добавлять #5 (номер текущей заявки). Тогда они будут отображаться здесь.
