### ISSUE TITLE
Вход и регистрация: Хранение данных

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#7]
### Хранение данных:
* [x] Организация множества логинов (первична скорость поиска)
* [x] Хранение информации об аккаунте
* [x] Проверка на доступность (по совпадениям) логина
* [x] Имя !== логин (возможно использовать одинаковые имена при различных логинах)

**Comment by Mazdaywik** [comment]
Поставьте, пожалуйста, в Linked pull requests соответствующие запросы на слияния.

**Comment by not-Whale** [comment]
@Klaus1901 @maksimellian сообщение выше для вас)
