### ISSUE TITLE
Если открыть корень, чат заново просит логин

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-1-chat#74]
Если открыть «корень» (стереть `/menu/〈имя-комнаты〉`), то сайт заново просит логин. Это так и должно быть?

И кнопка разлогина не работает. Она пока не реализована?

**Comment by Klaus1901** [comment]
Исправил, при открытии "корня" теперь открывается главная страница(если не авторизован- перекидывает на /login)
