### ISSUE TITLE
Вход и регистрация: Проверка на стороне пользователя

### ISSUE THREAD

**Issue by not-Whale** [bmstu-iu9/utp2020-1-chat#9]
### Необходимо реализовать скрипты для проверки корректности введенных данных при регистрации до отправки на сервер, а именно:
* [x] *Логин* - это последовательность символов латинского алфавита, цифр `0-9` и знаков `_`, `-`, длиной от 3 до 16 символов, *начинающаяся* с латинской буквы любого регистра.
* [x] *Пароль* - это последовательность символов латинского алфавита, цифр `0-9` и знаков `!`, `$`, `%`, `&`, `*`, `.`, `-`, `_`, `+`, `=`, длиной от 8 до 16 символов, в которой **обязательно** должна присутствовать хотя бы одна заглавная и одна прописная латинские буквы, а также хотя бы одна цифра.
* [x] *Имя (никнейм)* - это последовательность символов латинского алфавита, длиной от 3 до 24 символов **без** цифр и специальных знаков (подразумевается ввод своего имени или псевдонима).
* [x] В случае *неправильного* заполнения окна ввода логина/пароля/имени необходимо вывести **подсказку** для пользователя о правилах и ограничениях.
* [x] После проверки на соответствие правилам *можно* отправлять логин на **сервер** для получения ответа об уникальности.

**Comment by Mazdaywik** [comment]
Ага, вот как здесь сделано:
```
Решение проблемены #9:

Добавлены проверки пароля, логина, имени
В случае неправильного заполнения окон выводится подсказка для пользователя о правилах и ограничениях.
```
